name: phelel test using conda-forge environment

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda activate test
        conda install --yes -c conda-forge python=${{ matrix.python-version }}
        conda install --yes -c conda-forge phonopy phono3py finufft tomli tomli-w seekpath pytest click codecov pytest-cov
    - name: Setup phelel
      run: |
        conda activate test
        pip install -e . -vvv
    - name: Test with pytest
      run: |
        conda activate test
        velph --help
        phelel --help
        phelel-load --help
        pytest -v --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
